name: Publish Docker images
on:
  release:
    types: [published]
jobs:
  publish-to-github-packages:
    name: Push Docker image to GitHub Packages
    if: ${{ false }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Build and push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.ACTOR }}
          password: ${{ secrets.GITHUB_TOKEN }}
          repository: aspearman/static-website/static-website
          tag_with_ref: true
  publish-to-github-container-registry:
    name: Push Docker image to GitHub Container Registry
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          buildkitd-flags: --debug
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.ACTOR }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            aspearman/static-website:latest
            ghcr.io/aspearman/static-website:latest
